apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-azure-key-vault-provider-spc
  namespace: default
spec:
    provider: azure
    parameters:
      usePodIdentity: "false"
      useVMManagedIdentity: "false"
      userAssignedIdentityID: ""
      keyvaultName: ${KEYVAULT_NAME}
      objects:  |
        array:
          - |
            objectName: secret1
            objectType: secret
            objectVersion: ""
          - |
            objectName: secret2
            objectType: secret
            objectVersion: ""
          - |
            objectName: secret3
            objectType: secret
            objectVersion: ""
          - |
            objectName: secret4
            objectType: secret
            objectVersion: ""  
      tenantId: ${TENANT_ID}
